[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RobotKitLib"
authors = [{name = "Emily", email = "ethorpe@macalester.edu"}]
dynamic = ["version", "description"]
